### ISSUE TITLE
PEPPOL Schematron error

### ISSUE THREAD

**Issue by QAnders** [wvbe/node-schematron#1] opened 2019-11-20 12:36 UTC
First off, THANK YOU, I've been waiting for this for so long since we've built our PEPPOL (peppol.eu) Access Point in Node.js and Schematron validation have had to be run in a stand-alone JAVA (ugh!) App...

I tried it out using the official PEPPOL sch files but am getting an error:
```
(node:26429) UnhandledPromiseRejectionWarning: Error: XPST0017: Function matches with arity of 2 not registered. No similar functions found.
    at ng.J (/home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:260:278)
    at /home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:227:63
    at Array.forEach (<anonymous>)
    at ag.S.J (/home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:227:34)
    at ag.V.J (/home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:244:412)
    at ag.J (/home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:253:84)
    at /home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:227:63
    at Array.forEach (<anonymous>)
    at ug.S.J (/home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:227:34)
    at /home/anders/.nvm/versions/node/v10.15.3/lib/node_modules/node-schematron/node_modules/fontoxpath/dist/fontoxpath.js:227:63
(node:26429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26429) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Here's the `sch` that I've tried with: https://github.com/OpenPEPPOL/peppol-bis-invoice-3/blob/master/rules/sch/PEPPOL-EN16931-UBL.sch

Installed `node-schematron` globally on Linux running Node v10.15...

Any pointers?

**Comment by wvbe** [comment] 2019-11-21 01:16
Hey @QAnders , happy to hear I may have (almost) made someones day.

I haven't gotten round to supporting `<ns>` so I think the script tries to find a "matches" XPath function from the default namespace in your document XML, as opposed to finding it from the default namespace in the schematron XML. To be honest it catches me by surprise anyone even checks this stuff out so I had hoped to fix this before anybody would notice. I haven't been able to find a precise description of the way `<ns>` replaces/overrides/augments namespace information from the target document either.

To implement this the relevant information from `<ns>` needs to put unto the javascript model of what the schematron XML looks like (`Schema.ts` etc) so that it can be used cheaply, and to send it off to child processes. Then that information needs to be used as per whatever the specification is. I think configuring [fontoxpath](https://github.com/FontoXML/fontoxpath) with its `namespaceResolver`  option (`function(string): string?`) will be part of that, but I haven't looked into it further.

Let me know if that's not helpful. Because <ns> is part of schematron minimal syntax this aligns well with the goals of node-schematron.

**Comment by wvbe** [comment] 2019-11-21 01:21
I see that the README text may have been confusing around wether this should have worked or not. That's something that I'll fix in the short term ;)

**Comment by QAnders** [comment] 2019-11-21 09:07
Ah, thanks for getting back to me!
I mostly wanted to make sure I wasn't missing anything...

I don't want to stress you but I think ns's would be a needed addition as it is commonly used (for some strange reason...)

**Comment by wvbe** [comment] 2019-11-21 17:10
No worries :)

I've pushed a feature branch that contains namespace support for as far as I can tell how it works from the ISO PDF. I haven't extensively tested it yet (eg. default namespaces) but this is the gist of it.

Then I remembered that I should probably check if fontoxpath supports the "matches" function. ⚠️ [At this time that is not the case](https://documentation.fontoxml.com/editor/latest/xpath-25591894.html). So this is the next obstacle that needs to be tackled.

I happen to know that the maintainers of `fontoxpath` are very enthusiastic about adding features, and the lib is under active development. I would advice you to petition them to implement this further! After that `node-schematron` would hopefully only need to update its dependencies, because the `#ns` branch now theoretically contains `<ns>` support.

I'm leaving this issue open while I test <ns> support further, but I will close it when the remainder is support for `fn:matches` in `fontoxpath`. I would be interested to hear if you plan to reach out to fontoxpath, and if you do, what the outcome is.

Best,
Wybe

**Comment by wvbe** [comment] 2019-11-25 18:22
@QAnders , just a heads up that I'll close this issue later this week. I can not do more for it besides keeping `node-schematron` up to date. I hope you agree, let me know if there's any questions.

Thanks for pointing me to the `<ns />` support, I had fun coding that.

Ps. feel free to open a new issue if you run into trouble beyond the vocabulary implemented in `fontoxpath`

**Comment by wvbe** [comment] 2020-05-15 21:59
Reopening this issue because a new version of fontoxpath with `fn:matches` has been released!

**Comment by QAnders** [comment] 2020-11-09 17:02
I wanted to give this another whirl and I got closer I think but I am having issues adding the custom functions... 
I simply don't understand how to add them as I continue to get error messages like `XPST0017: Function u:slack with arity of 3 not registered. Did you mean "Q{utils}u:slack (xs:string?)"?`

The function is:
```
	<function xmlns="http://www.w3.org/1999/XSL/Transform" name="u:slack" as="xs:boolean">
		<param name="exp" as="xs:decimal"/>
		<param name="val" as="xs:decimal"/>
		<param name="slack" as="xs:decimal"/>
		<value-of select="xs:decimal($exp + $slack) &gt;= $val and xs:decimal($exp - $slack) &lt;= $val"/>
	</function>
```
The `ns` is `xmlns:u="utils"`.

If I remove the function from the SCH it runs through and lists all assertions/rules just fine!

Please let me know if you'd like to pursue this and I can supply sample data for the PEPPOL SCH!

I had some invalid utf-8 chars messing up the SCH but now the actual SCH for everything but the Functions works!!!!

Superb!

I'd would need to get the functions in though so any pointer on how I can solve that would be very much appreciated!

**Comment by wvbe** [comment] 2020-11-10 21:04
Hey @QAnders, registering custom functions is not a feature of `node-schematron`, or at least yet. The error you're getting suggests that the `u:slack` function isn't registered yet (although it also suggests `u:slack` with a single argument _does_ exist, I dunno about that).

It _is_ a feature of the underlying XPath engine, `fontoxpath`, but it'll take a little parsing in `node-schematron` to tie everything together. If I were to make a guess, it's probably easiest to generate an XPath function based on the info in the `param` and `value-of` elements. I suppose your code snippet would be equivalent to the following;

```xquery
declare function u:slack ($exp, $val, $slack) as xs:boolean {
    xs:decimal($exp + $slack) >= $val and xs:decimal($exp - $slack) <= $val
}
```

If you were to be able to generate the above code snippet as a string from your XML, and then use `fontoxpath`'s `registerXQueryModule`, I'm gonna guess that might work!

(Another way would be to use fontoxpath's AST parsing somehow, but I'm not sure if that has any consequential advantages over my "easy" suggestion)

Obviously I would be happy to look at any pull-request you might make ;) I expect this'd probably take a few hours, and might need a better look at `<ns>` also.

I would hesitate to promise you anything from my side because `node-schematron` comes out of my free time and all. If, however, that means you are stuck so close to the finish line (congrats on getting everything else to work!) I'd be willing to give it a shot -- I have some free time coming up around the December holidays. In that case I would have to go by your SCH examples and maybe some guidance if you have experience with Schematron. I could learn something, and you might walk away with a working software ;)

Regards,
Wybe

**Comment by wvbe** [comment] 2020-11-10 23:22
@QAnders does your `<function>` usage correlate with these docs?
https://www.saxonica.com/html/documentation/xsl-elements/function.html

**Comment by judescripts** [comment] 2020-12-29 01:09
I'm getting the same issue and my schematron schema has a lot of custom functions... was so excited to use this library but currently doesn't support what we need done yet. I'm probably going to resort back to using saxon-js and converting it to xslt for processing, but looking forward to an update for this in the near future. I'm not an expert on schematron but my current project requires me to use it for an application that requires schematron validation for government standards and using their schema with many different custom functions. I'd be happy to help out in whatever capacity you need in the future to make this work for more complex version of schematron.

**Comment by wvbe** [comment] 2020-12-30 11:18
@judescripts thank you for that offer.

Right now I'm trying to estimate which "extra" features are actually useful, and what is expected of them from a standards perspective. To my knowledge, custom functions is not "in the schematron spec", but there is actually a lot that isn't in there. Although I'm not opposed to implementing custom functions (its probably fun), I'd like to have a clear picture of what would then also be expected in scope, and what remains out of scope.

Can you confirm that your custom schematron functions syntax is per the documentation on https://www.saxonica.com/html/documentation/xsl-elements/function.html ? If not, could you point me to documentation sources?

Thanks!

**Comment by QAnders** [comment] 2020-12-30 11:54
> @QAnders does your `<function>` usage correlate with these docs?
> https://www.saxonica.com/html/documentation/xsl-elements/function.html

Sorry for the late come-back! :(

Yes, those would be the functions. I've attached the SCH file I have been testing with for PEPPOL:

[PEPPOL-EN16931-UBL.sch.txt](https://github.com/wvbe/node-schematron/files/5754090/PEPPOL-EN16931-UBL.sch.txt)

**NB!** I've removed (commented) the functions now so remove the `<!--  -->` comments to add the functions!

**Comment by wvbe** [comment] 2020-12-30 23:08
I'm sad to say that the spec for `xsl:function` is far greater than what I can implement on my own. Some of the examples in the PEPPOL file are simple. Eg, the following from the PEPPOL file should work on branch `xslt-function`:

```xml
<function xmlns="http://www.w3.org/1999/XSL/Transform" name="u:slack" as="xs:boolean">
  <param name="exp" as="xs:decimal"/>
  <param name="val" as="xs:decimal"/>
  <param name="slack" as="xs:decimal"/>
  <value-of select="xs:decimal($exp + $slack) &gt;= $val and xs:decimal($exp - $slack) &lt;= $val"/>
</function>
```

Because it's the same as XQuery;

```xq
declare %public function u:slack($exp: xs:decimal, $val: xs:decimal, $slack: xs:decimal) {
  xs:decimal($exp + $slack) >= $val and xs:decimal($exp - $slack) <= $val
}
```

However, it quickly gets more complicated when `<xsl:variable>` is introduced, or any of `xsl:if`, `xsl:for-each`, `xsl:choose`, etc. Specifically, [sequence constructors](https://www.w3.org/TR/xslt-30/#dt-sequence-constructor). A [random](https://www.oxygenxml.com/forum/topic13057.html) example that demonstrates this;

```xml
<xsl:function name="local-fn:BuildLookupExpression" as="xs:string">
  <xsl:param name="TableName" as="xs:string" />
  <xsl:text>(</xsl:text>
  <xsl:for-each select="key('Code-Lookup', $TableName)/Code">
    <xsl:value-of select="." />
    <xsl:if test="position() != last()">
      <xsl:text>)|(</xsl:text>
    </xsl:if>
    <xsl:if test="position() = last()">
      <xsl:text>)</xsl:text>
    </xsl:if>
  </xsl:for-each>
</xsl:function>
```

I'm leaving an experiment on branch `xslt-function` because the wiring is set-up but the logic of creating an XQuery program out of that XSLT syntax will take a lot more. Who knows someone wants to tinker with it, or take a different approach altogether. Maybe yourselves can make the necessary additions to support the subset of `xsl:function` that you use.

Sorry @QAnders , @judescripts

**Comment by QAnders** [comment] 2020-12-31 10:16
Thanks @wvbe you work is very much appreciated!

It would be so nice getting this working so if I can scramble up some time I might look into it but don't get your hopes up as I am no super-coder... :)

**Comment by judescripts** [comment] 2021-01-02 19:02
> I'm sad to say that the spec for `xsl:function` is far greater than what I can implement on my own. Some of the examples in the PEPPOL file are simple. Eg, the following from the PEPPOL file should work on branch `xslt-function`:
> 
> ```
> <function xmlns="http://www.w3.org/1999/XSL/Transform" name="u:slack" as="xs:boolean">
>   <param name="exp" as="xs:decimal"/>
>   <param name="val" as="xs:decimal"/>
>   <param name="slack" as="xs:decimal"/>
>   <value-of select="xs:decimal($exp + $slack) &gt;= $val and xs:decimal($exp - $slack) &lt;= $val"/>
> </function>
> ```
> 
> Because it's the same as XQuery;
> 
> ```xq
> declare %public function u:slack($exp: xs:decimal, $val: xs:decimal, $slack: xs:decimal) {
>   xs:decimal($exp + $slack) >= $val and xs:decimal($exp - $slack) <= $val
> }
> ```
> 
> However, it quickly gets more complicated when `<xsl:variable>` is introduced, or any of `xsl:if`, `xsl:for-each`, `xsl:choose`, etc. Specifically, [sequence constructors](https://www.w3.org/TR/xslt-30/#dt-sequence-constructor). A [random](https://www.oxygenxml.com/forum/topic13057.html) example that demonstrates this;
> 
> ```
> <xsl:function name="local-fn:BuildLookupExpression" as="xs:string">
>   <xsl:param name="TableName" as="xs:string" />
>   <xsl:text>(</xsl:text>
>   <xsl:for-each select="key('Code-Lookup', $TableName)/Code">
>     <xsl:value-of select="." />
>     <xsl:if test="position() != last()">
>       <xsl:text>)|(</xsl:text>
>     </xsl:if>
>     <xsl:if test="position() = last()">
>       <xsl:text>)</xsl:text>
>     </xsl:if>
>   </xsl:for-each>
> </xsl:function>
> ```
> 
> I'm leaving an experiment on branch `xslt-function` because the wiring is set-up but the logic of creating an XQuery program out of that XSLT syntax will take a lot more. Who knows someone wants to tinker with it, or take a different approach altogether. Maybe yourselves can make the necessary additions to support the subset of `xsl:function` that you use.
> 
> Sorry @QAnders , @judescripts

No problem and thank you, yes my current requirements uses almost all xsl:function that you've described above. I'd love to help out in the future on adding these functionalities. I would love a quick intro to your current code base and what you are thinking and maybe I can start contributing to this project together. It's a shame that there are no good schematron implementation in node and I think it would bring tremendous value. Maybe even get an opensource sponsor to get this project rolling in the future. Thanks for all your help @wvbe and Happy New Year!

**Comment by wvbe** [comment] 2021-01-03 12:20
Hey @judescripts I appreciate that. I'd be totally up for an intro like that, do you imagine a conference call works well for that? I understand if that does not have your preference, no pressure :) I've sent you a connect request on LinkedIn so we can share contact info there if you want.

I hope a solution lies in XQuery and the XQuery AST that `fontoxpath` uses ([it's used internally](https://github.com/FontoXML/fontoxpath/blob/master/src/parseScript.ts#L158)). IIRC it is an XML-ish object. If we can transform the XSLT elements into an XQuery AST, that sounds like a solid solution as opposed to just patchwork. _However, I don't know if there is any overlap between the AST and XSLT at all._ I'm sure some of XSLT's native functionality will be tricky to translate to XQuery functions etc.

It's quite possible that XQuery is not the way to go here, in which case I think we're looking at writing more traditional set of functions. Probably a bunch of code and/or interesting as a `node_module` in its own right. That might however  require someone more formally trained in algorithmic efficiency etc. than myself 😬 

Many thanks for both your enthousiasm, and a happy 2021 to you too!

**Comment by judescripts** [comment] 2021-01-03 18:41
> Hey @judescripts I appreciate that. I'd be totally up for an intro like that, do you imagine a conference call works well for that? I understand if that does not have your preference, no pressure :) I've sent you a connect request on LinkedIn so we can share contact info there if you want.
> 
> I hope a solution lies in XQuery and the XQuery AST that `fontoxpath` uses ([it's used internally](https://github.com/FontoXML/fontoxpath/blob/master/src/parseScript.ts#L158)). IIRC it is an XML-ish object. If we can transform the XSLT elements into an XQuery AST, that sounds like a solid solution as opposed to just patchwork. _However, I don't know if there is any overlap between the AST and XSLT at all._ I'm sure some of XSLT's native functionality will be tricky to translate to XQuery functions etc.
> 
> It's quite possible that XQuery is not the way to go here, in which case I think we're looking at writing more traditional set of functions. Probably a bunch of code and/or interesting as a `node_module` in its own right. That might however require someone more formally trained in algorithmic efficiency etc. than myself 
> 
> Many thanks for both your enthousiasm, and a happy 2021 to you too!

Sounds good and conference call sounds great. Reached back out on Linkedin. Let's continue to the convo there and possibly set up a slack/discord channel where people can collaborate for this project. Chat soon!

**Comment by wvbe** [comment] 2021-02-04 23:01
@QAnders just a heads up, I've managed to implement some `xslt` function elements beyond what I had initially expected. I'm still running into some weird stuff sometimes when I try it out on your PEPPOL repository, but _not always_, so thats encouraging.

Do you know if, out of the 230-something XML files in the PEPPOL repository, how many validation errors are expected? Right now results vary between a bug on `node-schematron`'s feature branch, or no validation errors, and I was wondering if that sounds about right? Which XML elements should the `rules/sch/PEPPOL-EN16931-UBL.sch` schema apply to, if not every XML file?

Thanks!

**Comment by QAnders** [comment] 2021-02-05 06:20
Wow, cool! Nice job!

The Schematron shall be run on invoice and creditnote only. 
If you supply me with an email address I can send to I can share a few invoices and also an API I've built in Java (ugh) so you can compare....

**Comment by wvbe** [comment] 2021-02-05 08:44
Hey @QAnders, `github@x-54.com` is my public adress, feel free to send it there. Don't bother with the Java, I don't think I have it installed and tbh I prefer it that way. Do you maybe have a text dump of the schematron output, or screenshot instead?

Edit: I'm getting some results that (although I don't know if these are invoices/creditnotes) look realistic. You might be able to check them youtself:

```
fail rules/unit-UBL-PEPPOL/PEPPOL-EN16931-P0108.xml
asrt  ✘  PEPPOL-EN16931-R001  Business process MUST be provided.
asrt  ✘  PEPPOL-EN16931-R007  Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
asrt  ✘  PEPPOL-EN16931-R003  A buyer reference or purchase order reference MUST be provided.
asrt  ✘  PEPPOL-EN16931-R004  Specification identifier MUST have the value 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'.
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R001  Business process MUST be provided.
asrt  ✘  PEPPOL-EN16931-R007  Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
asrt  ✘  PEPPOL-EN16931-R003  A buyer reference or purchase order reference MUST be provided.
asrt  ✘  PEPPOL-EN16931-R004  Specification identifier MUST have the value 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'.
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R001  Business process MUST be provided.
asrt  ✘  PEPPOL-EN16931-R007  Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
asrt  ✘  PEPPOL-EN16931-R003  A buyer reference or purchase order reference MUST be provided.
asrt  ✘  PEPPOL-EN16931-R004  Specification identifier MUST have the value 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'.
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-P0108  Tax Category E MUST be used when exemption reason code is VATEX-EU-D
asrt  ✘  PEPPOL-EN16931-P0108  Tax Category E MUST be used when exemption reason code is VATEX-EU-D
fail rules/unit-UBL-PEPPOL/PEPPOL-EN16931-P0111.xml
asrt  ✘  PEPPOL-EN16931-R001  Business process MUST be provided.
asrt  ✘  PEPPOL-EN16931-R007  Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
asrt  ✘  PEPPOL-EN16931-R003  A buyer reference or purchase order reference MUST be provided.
asrt  ✘  PEPPOL-EN16931-R004  Specification identifier MUST have the value 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'.
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R001  Business process MUST be provided.
asrt  ✘  PEPPOL-EN16931-R007  Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
asrt  ✘  PEPPOL-EN16931-R003  A buyer reference or purchase order reference MUST be provided.
asrt  ✘  PEPPOL-EN16931-R004  Specification identifier MUST have the value 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'.
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R001  Business process MUST be provided.
asrt  ✘  PEPPOL-EN16931-R007  Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
asrt  ✘  PEPPOL-EN16931-R003  A buyer reference or purchase order reference MUST be provided.
asrt  ✘  PEPPOL-EN16931-R004  Specification identifier MUST have the value 'urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0'.
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-R051  All currencyID attributes must have the same value as the invoice currency code (BT-5), except for the invoice total VAT amount in accounting currency (BT-111).
asrt  ✘  PEPPOL-EN16931-P0111  Tax Category E MUST be used when exemption reason code is VATEX-EU-J
asrt  ✘  PEPPOL-EN16931-P0111  Tax Category E MUST be used when exemption reason code is VATEX-EU-J
```

**Comment by QAnders** [comment] 2021-06-30 10:03
I am very sorry for the looong come back here but I haven't had time to dig into this further... I have now played around with it and it runs the functions from the Peppol schematron real nicely now!
Real nice! Thanks!

However, the execution time is show-stopper:
![image](https://user-images.githubusercontent.com/12028885/123941612-9d2b8c80-d99a-11eb-8e6f-549337cf152f.png)

I do realize that it is a heavy burden to run it but figured if it would somehow be possible to cache/re-compile some of the rules similar to what AJV does with stand-alone?
https://github.com/ajv-validator/ajv/blob/master/docs/standalone.md

I haven't looked into the code so not sure if it is an option but figured it probably builds "JS rules" from the XSLT/Schematron and if those could be "stored" as pre-compiled schemas it might gain some time...

**Comment by QAnders** [comment] 2021-06-30 10:45
Did some more testing and seems the functions are still not working... :(
```
/home/anders/CodeStuff/cda-schematron/node_modules/fontoxpath/dist/fontoxpath.js:229
u).fill("^",u,t).join(""))}return k},[]);d=qm(d).join("\n");throw new nm(c.join("\n")+"\n\n"+d,f);};function Y(c,d){"*"===d||Array.isArray(d)||(d=[d]);for(var f=1;f<c.length;++f)if(Array.isArray(c[f])){var e=c[f];if("*"===d||d.includes(e[0]))return e}return null}function rm(c){return 2>c.length?"":"object"===typeof c[1]?c[2]||"":c[1]||""}function sm(c,d){if(!Array.isArray(c))return null;c=c[1];return"object"!==typeof c||Array.isArray(c)?null:d in c?c[d]:null}function tm(c,d){return d.reduce(Y,c)}
                                                            ^
nm [Error]: 1: matches(normalize-space(), '^[0-9]+$') and u:gln(normalize-space())
                                              ^^^^^^^^^^^^^^^^^^^^^^^^

Error: XPST0017: Function u:gln with arity of 1 not registered. No similar functions found.
  at <functionCallExpr>:1:44 - 1:68
  at <andOp>:1:1 - 1:68
    at new nm (/home/anders/CodeStuff/cda-schematron/node_modules/fontoxpath/dist/fontoxpath.js:228:786)
    at om (/home/anders/CodeStuff/cda-schematron/node_modules/fontoxpath/dist/fontoxpath.js:229:67)
    at Ju (/home/anders/CodeStuff/cda-schematron/node_modules/fontoxpath/dist/fontoxpath.js:670:613)
    at Object.Qu [as evaluateXPathToBoolean] (/home/anders/CodeStuff/cda-schematron/node_modules/fontoxpath/dist/fontoxpath.js:673:640)
    at Assert.validateNode (/home/anders/CodeStuff/cda-schematron/node_modules/node-schematron/dist/node-schematron.cjs.development.js:100:30)
    at /home/anders/CodeStuff/cda-schematron/node_modules/node-schematron/dist/node-schematron.cjs.development.js:146:21
    at Array.map (<anonymous>)
    at Rule.validateNode (/home/anders/CodeStuff/cda-schematron/node_modules/node-schematron/dist/node-schematron.cjs.development.js:145:25)
    at flattenValidationResults (/home/anders/CodeStuff/cda-schematron/node_modules/node-schematron/dist/node-schematron.cjs.development.js:190:71)
    at Array.reduce (<anonymous>)
```

I've been trying to add the `registerCustomXPathFunction` but can't get it working...

**Comment by wvbe** [comment] 2021-06-30 12:08
Hey @QAnders , thanks for taking the time for test running it _and_ feeding it back here!

With regards to caching or pre-compiling schemas; I've never really spent a lot of time on the performance aspect of this yet. I imagine most of the time currently is spent on running the functions used in assertions etc. with different XML nodes all the time. I have not verified this. Also, since recently `fontoxpath` (the driver of all things XPath) has released a way to precompile expressions -- this might help a lot with a little implementation effort. For tracking sake, it'd probably be better to log that as a separate issue for now.

With regards to the error you're experiencing, I would be fine to look into it but I would need a reproduction case (eg. the Schematron and XML files, and the input you've given through the terminal). @judescripts created a Slack space that we're both on, and you might join it to share any reproduction  files in a slightly less public fashion :) Here is an invite link in case you want to give it a spin:

https://join.slack.com/t/node-schematron/shared_invite/zt-shngabec-MVTSCSPi3VxRVHfy13TjmQ

All the best,
Wybe

**Comment by wvbe** [comment] 2021-07-01 22:03
@QAnders I just realised you might not have ran `npm run build` after switching to the `xslt-functions` branch, or after trying out `registerCustomXPathFunction`.

If you have `node-schematron` `npm link`'ed, keep a terminal open in it and run `npm start` -- this will start a watch task and recompile the executable on every Typescript change. Courtesy of TSDX.

**Comment by wvbe** [comment] 2021-07-04 09:34
**I've found the cause of the error that kept preventing me from running one of the PEPPOL schemas, and I don't think I can solve it.**

In schematron (or XSLT?) there are situations in which a schema may use a "global" variable that depends on the document. For example (truncated);


```xml
<schema>
  <ns uri="http://foo" prefix="foo" />
  <let name="baz" value="/*" />
  <xsl:function name="foo:bar">
    <xsl:value-of select="$baz" />
  </xsl:function>
</schema>
```

... translates to the following XQuery function in the `foo` library module:

```xq
declare %public function foo:bar() {
  $baz
}
```

The `$baz` variable can then only be declared (AFAIK) in two unhelpful ways; as `let $baz := /*` in the XQuery function, or as `declare variable $baz := /*` at the top of the (library) module. In both cases, the context necessary for `/*` is not available.

To fix, I've considered:
- Generating `foo:bar` with argument `$baz`, but I would have to update the callsites of `foo:bar` too (which I cannot, without opening up a whole new can of AST or RegExp works)
- Throwing everything in the same (main) module, but this destroys all concept of namespacing
- Calculating `baz` before execution entirely, and pass it into the query that calls `foo:bar` using `fontoxpath` `evaluateXPath`'s `variables` option. Unfortunately, it will still tell me `The variable baz is not in scope`.

**Unfortunately, I think the "XSLT to XQuery" approach is therefore a dead end, and I'm forced to abandon this issue. I'll keep the feature branch around because it doesn't hurt anyone, but I don't think it is fit for integration.**

**Closed as completed by wvbe** 2021-07-04 09:34 UTC
Labels: enhancement, help wanted, unsolved

**Comment by karladler** [comment] 2025-03-26 09:17
Have you considered implementing it in 2025? My guess is, that this can be resolved with the help of some LLMs.
I would be glad if this can be implemented. There probably would be a need also since e-invoice us gonna be mandatory in EU soon.

**Comment by QAnders** [comment] 2025-03-26 11:32
Maybe not the answer here, but I've worked some on the node solution for "complex" schematron here: https://github.com/QAnders/schematrode

We have full XSLT 2.0 support now, so it would be possible to handle...
